### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by ItsBrogan** [zsawyer/MumbleLink#37] opened 2021-02-18 16:42 UTC
Not entirely sure what's going on. The server won't load when I have the mod on. 

Removed all other mods to ensure it's not a conflict. Forge version 1.16.5-36.0.42

Using mumble link version 4.6.3

I've attached the crash logs
[crash-2021-02-18_08.39.01-fml.txt](https://github.com/zsawyer/MumbleLink/files/6004451/crash-2021-02-18_08.39.01-fml.txt)

**Comment by Robijnvogel** [comment] 2021-02-20 11:01
duplicate of #12

**Closed as completed by Robijnvogel** 2021-02-20 11:01 UTC
