### ISSUE TITLE
MumbleLink doesn't update player position

### ISSUE THREAD

**Issue by Snorps** [zsawyer/MumbleLink#14] opened 2017-04-10 10:43 UTC
MumbleLink just sends Crosstalk the spawn co-ordinates of the current server, rather than the players co-ordinates. Tested on 3 separate computers, MumbleLink version 4.2.4, Crosstalk 1.7.0 and 1.6.3.111601, Forge 13.19.1.2189.

**Comment by nicktrick92** [comment] 2017-06-06 21:31
Confirmed that it does not properly send position to TeamSpeak through CrossTalk... I just get the following all the time: 

Playing Minecraft as {"name":"nick_the_mc_boss","worldSpawn":[52,53,206],"dimension":0}.

It does work for me on mumble, but it does not seem to work on TeamSpeak... Could it be a CrossTalk issue?

**Comment by Robijnvogel** [comment] 2017-06-06 22:10
Without a MumbleLink version AND a CrossTalk version, this will be rather hard to troubleshoot.

**Comment by nicktrick92** [comment] 2017-06-08 15:58
Sorry, I meant to come back and add them but I forgot... For me, I;ve tried with mumbleLink 1.9.4, 1.10, 1.10.2, and 1.11 (At separate times, to ensure it wasn't the version that was the issue) and Crosstalk version, I'm not sure about the exact version number, but it's the most recent one (Updated on 2017-02-20)... I'm thinking maybe the CrossTalk version is too new, but i couldn't find any other downloads! @Robijnvogel

**Comment by Robijnvogel** [comment] 2017-06-12 13:15
Since the issue does not occur with Mumble, I assume that this is a Crosstalk bug.

**Comment by zsawyer** [comment] 2017-07-18 23:46
Sorry, even though I endorse the crosstalk plugin the main criteria is that it works in mumble. 
Thank you for the detailed report, but I am closing this as I agree with @Robijnvogel that this needs to be solved in the crosstalk plugin itself.

**Closed as completed by zsawyer** 2017-07-18 23:46 UTC

**Comment by Hedrauta** [comment] 2017-10-24 02:29
... Using Mumblelink 4.1.1 for MC 1.7.10: checking the logs on debug-mode.... plugin only sends one command:
[04:26:46] [Client thread/INFO] [MumbleLink]: identity: {"name":"Hedrauta","worldSpawn":[48,64,256],"dimension":0}
[04:26:46] [Client thread/INFO] [MumbleLink]: context: {"domain":"AllTalk"}
No position-update at all.... used Crosstalk 1.7.0 on Forge 10.13.4.1614 with ONLY active Mumblelink-addon
Still a bug?

**Comment by Hedrauta** [comment] 2017-10-24 03:38
https://github.com/zsawyer/MumbleLink/blob/8801ffc16950b7376f6710bb96091b11e26fa55e/mod/src/main/java/zsawyer/mods/mumblelink/addons/pa/es/ExtendedPASupport.java#L160
Why are you fetching the spawn? it should be the players location... or do i misunderstand that mod?
[EDIT]
tried to fetch the source code from 4.1.1 and rebuild on my own. failed hard...

**Comment by Robijnvogel** [comment] 2017-10-26 07:12
Indeed, fetching the spawn does not seem to have an obvious purpose.
Then again, the MumbleLink mod also fetches the player's actual location or at least its location relative to spawn. Otherwise the mod wouldn't work with Mumble either.

**Comment by zsawyer** [comment] 2017-12-17 12:00
Above that code line it tells you why...

https://github.com/zsawyer/MumbleLink/blob/8801ffc16950b7376f6710bb96091b11e26fa55e/mod/src/main/java/zsawyer/mods/mumblelink/addons/pa/es/ExtendedPASupport.java#L156

        '// build spawn location coordinates (sadly this is the only somewhat
        // identifiable information the client has about the world (and server)
        // it connects to.'

The log is perfectly fine. The mod will not log each position update as it would be way too spammy. 

with that log enrtry you are looking at the static identity information. This is needed if mumble server wants to differentiate between players in different worlds and dimensions. It is simply there for uniqueness and if some one will write the mumo plugin for minecraft. 

If you want to see what the mod sends use MumblePAhelper. This is the source of truth to use.
